services:
  draws_index:
    build: ./draws_index
    container_name: draws_index
    ports:
      - "127.0.0.63:8539:8080"
    volumes:
      - ./draws_index/jid_authorname_map:/app/jid_authorname_map
      - ./draws_index/db:/app/db
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
